export const Authaction = {
  SET_TOKEN: "SET_TOKEN",
  SET_USER: "SET_USER",
  SET_AUTH_LOADING: "SET_AUTH_LOADING",
};

export const DataAction = {
  SET_CATEGORIES: "SET_CATEGORIES",
  SET_VIDEOS: "SET_VIDEOS",
  ADD_TO_PLAYLIST: "ADD_TO_PLAYLIST",
  // liked
  GET_LIKE_VIDEOS: "GET_LIKE_VIDEOS",
  ADD_TO_LIKED: "ADD_TO_LIKED",
  REMOVE_FROM_LIKED: "REMOVE_FROM_LIKED",
  // watchlater
  GET_WATCH_LATER_VIDEOS: "GET_WATCH_LATER_VIDEOS",
  ADD_TO_WATCH_LATER: "ADD_TO_WATCH_LATER",
  REMOVE_FROM_WATCH_LATER: "REMOVE_FROM_WATCH_LATER",
  SORT_BY_CATEGORY: "SORT_BY_CATEGORY",
};
