export const Authaction = {
  SET_TOKEN: "SET_TOKEN",
  SET_USER: "SET_USER",
  SET_AUTH_LOADING: "SET_AUTH_LOADING",
};

export const DataAction = {
  SET_CATEGORIES: "SET_CATEGORIES",
  SET_VIDEOS: "SET_VIDEOS",
  ADD_TO_PLAYLIST: "ADD_TO_PLAYLIST",
  SET_LIKE_VIDEOS: "SET_LIKE_VIDEOS",
  SET_HISTORY_VIDEOS: "SET_HISTORY_VIDEOS",
  SET_WATCH_LATER_VIDEOS: "SET_WATCH_LATER_VIDEOS",
  ADD_TO_WATCH_LATER: "ADD_TO_WATCH_LATER",
  SET_SEARCH_VIDEO: "SET_SEARCH_VIDEO",
  SET_SORT_CATEGORY: "SET_SORT_CATEGORY",
};
